theme: "just-the-docs"
url: http://localhost:4000/
  
title: StackState ETL
description: >- 
  This site is for the documentation of StackState ETL framework

aux_links:
  "StackState ETL on GitHub":
    - "//github.com/stackstate-lab/stackstate-etl"
  
compress_html:
  # clippings: all
  # comments: all
  # endings: all
  # startings: []
  blanklines: true
  # profile: false
  # ignore:
  #   envs: all

exclude: []


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2020-2022 <a href=\"http://stackstate.com\">StackState</a>."
